import { Slider } from "./Slider";
import PlaybackModeButton from "./PlaybackModeButton";
import type { PlaybackMode } from "../playbackOrder";
import { memo, type ReactNode } from "react";
import { GlassRefraction } from "./GlassRefraction";
import { Info, Pause, Play, RotateCcw, Volume2, ListMusic, SkipBack, SkipForward } from "lucide-react";

export interface TrackInfo {
  codec: string;
  sampleRate: number;
  /** Container/header channel_count. For EC-3 JOC this can be its 2-channel core. */
  channels: number;
  container: string;
  /** Duration declared by the container header, when present. */
  durationSec?: number;
  /** Actual fixed E-AC-3/other codec channels before object reconstruction. */
  rawBedLabels?: string[];
  /** Object URL for embedded MP4/MKV cover art, when available. */
  coverUrl?: string;
  /** Decoded fixed bed labels from actual PCM frames. */
  bedLabels?: string[];
  /** Decoded dynamic object PCM channels from actual PCM frames. */
  objectChannels?: number;
  /** True when SDA identified the decoded master as ordinary stereo. */
  stereoSource?: boolean;
  /** True when the displayed bed was generated by SDA's ALAC upmixer. */
  upmixed?: boolean;
  /** 歌曲标题：容器元数据（MKV Title / 音轨 Name）或文件名兜底。 */
  title?: string;
  artist?: string;
  album?: string;
}

interface MiniPlayerProps {
  children?: ReactNode;
  track: TrackInfo | null;
  position: number;
  /** 已解码总时长（秒）。流式解码中持续增长，读完即为全长；0 表示未知。 */
  duration: number;
  playing: boolean;
  paused: boolean;
  objectCount: number;
  volume: number;
  onPrevious: () => void;
  onNext: () => void;
  canSkip: boolean;
  onTogglePlay: () => void;
  playbackMode: PlaybackMode;
  onPlaybackModeChange: (mode: PlaybackMode) => void;
  playlistOpen: boolean;
  onTogglePlaylist: () => void;
  onShowMetadata: () => void;
  onReplay: () => void;
  onVolume: (v: number) => void;
}

function formatTime(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

export const MiniPlayer = memo(function MiniPlayer({
  children,
  track,
  position,
  duration,
  playing,
  paused,
  objectCount,
  volume,
  onPrevious,
  onNext,
  canSkip,
  onTogglePlay,
  playbackMode,
  onPlaybackModeChange,
  playlistOpen,
  onTogglePlaylist,
  onShowMetadata,
  onReplay,
  onVolume,
}: MiniPlayerProps) {
  if (!track) return null;
  const progress = duration > 0 ? Math.min(1, position / duration) : 0;
  return (
    <div className={`miniplayer ${window.sdaDesktop?.rendererMode === "swiftshader" ? "software-renderer" : ""}`}>
      <div className="mp-glass">
        <GlassRefraction />
        <div className="mp-bar">
          {/* 左：封面 + 曲名 */}
          <div className="mp-left">
            <div className={`mp-art ${track.coverUrl ? "has-cover" : ""} ${playing && !paused ? "playing" : ""}`}>
              {track.coverUrl ? <img src={track.coverUrl} alt="" /> : <><span /><span /><span /><span /></>}
            </div>
            <div className="mp-meta">
              <div className="mp-title-row">
                <div className="mp-title">{track.title ?? track.codec}</div>
                <button type="button" className="mp-info" onClick={onShowMetadata} aria-label="查看歌曲元数据" title="歌曲元数据">
                  <Info size={15} strokeWidth={2} aria-hidden="true" />
                </button>
              </div>
              <div className="mp-sub">
                {track.codec} · {(track.sampleRate / 1000).toFixed(1)} kHz · {track.rawBedLabels?.length ? `${track.rawBedLabels.length} 原始声道` : track.rawBedLabels ? "无声道床" : "等待首帧"} · {track.objectChannels ? `${track.objectChannels} 对象` : "无对象"} · {track.container}
              </div>
            </div>
          </div>

          {/* 中：传输控制 + 进度 */}
          <div className="mp-center">
            <div className="mp-transport">
              <button className="mp-btn mp-replay" onClick={onReplay} aria-label="从头重新播放">
                <RotateCcw size={17} strokeWidth={1.8} aria-hidden="true" />
              </button>
              <button type="button" className="mp-btn" onClick={onPrevious} disabled={!canSkip} aria-label="上一曲" title="上一曲"><SkipBack size={18} fill="currentColor" aria-hidden="true" /></button>
              <button
                className="mp-btn mp-play"
                onClick={onTogglePlay}
                aria-label={playing && !paused ? "暂停" : paused ? "继续" : "播放"}
              >
                {playing && !paused ? <Pause size={16} fill="currentColor" strokeWidth={1.5} aria-hidden="true" /> : <Play size={16} fill="currentColor" strokeWidth={1.5} aria-hidden="true" />}
              </button>
              <button type="button" className="mp-btn" onClick={onNext} disabled={!canSkip} aria-label="下一曲" title="下一曲"><SkipForward size={18} fill="currentColor" aria-hidden="true" /></button>
              <PlaybackModeButton mode={playbackMode} onChange={onPlaybackModeChange} className="mp-btn" />
              <button type="button" className="mp-btn mp-playlist" onClick={onTogglePlaylist}
                aria-label="播放列表" aria-expanded={playlistOpen} title={playlistOpen ? "收起播放列表" : "打开播放列表"}>
                <ListMusic size={18} strokeWidth={1.8} aria-hidden="true" />
              </button>
            </div>
            <div className="mp-progress">
              <span className="mp-time">{formatTime(position)}</span>
              <div className="mp-track-line" aria-label="播放进度">
                <div className="mp-track-fill" style={{ transform: `scaleX(${progress})` }} />
                {duration <= 0 && <div className="mp-track-shimmer" />}
              </div>
              <span className="mp-time dim">{duration > 0 ? formatTime(duration) : "--:--"}</span>
            </div>
          </div>

          {/* 右：对象数 + 音量 */}
          <div className="mp-right">
            <span className="mp-objs">{objectCount} 对象</span>
            <div className="mp-vol" title="音量">
              <span className="mp-vol-icon"><Volume2 size={18} /></span>
              <Slider
                aria-label="音量"
                min={0}
                max={100}
                value={Math.round(volume * 100)}
                onChange={(e) => onVolume(Number(e.target.value) / 100)}
              />
            </div>
          </div>
        </div>
      </div>
      {playlistOpen && children}
    </div>
  );
});
