import {leb} from './diagnostic-framing';
import {codecFailure,codecCheckpoint} from './codec-checkpoints';
import type {DecodedFrameData,ObjectEvent} from './index.js';
// @ts-ignore generated by scripts/build-iamf.mjs
import createModule from '../pkg-iamf/iamf.js';
// @ts-ignore Vite asset
import wasmUrl from '../pkg-iamf/iamf.wasm?url';
let runtime:any,loading:Promise<void>|undefined;
export function initIamf():Promise<void>{return loading??=createModule({locateFile:()=>wasmUrl}).then((m:any)=>{runtime=m;});}
export function isIamf(b:Uint8Array):boolean{if(b[0]!==0xf8)return false;const n=leb(b,1);return !!n&&b[n[1]]===105&&b[n[1]+1]===97&&b[n[1]+2]===109&&b[n[1]+3]===102;}
const beds=['L','R','C','LFE','Ls','Rs','Lb','Rb','Tfl','Tfr','Tbl','Tbr'];
/** Raw IAMF, pinned Advanced-2 reference decoder. Objects stay separate from the 7.1.4 bed. */
export class IamfDecoder{
 private pending=new Uint8Array(0);private frames:DecodedFrameData[]=[];private samplePos=0;private dead=false;private ids=new Map<string,number>();
 constructor(){if(!runtime)throw codecFailure("iamf.failure_01",'IAMF runtime not initialized');if(runtime._sda_open())throw codecFailure("iamf.failure_02",'IAMF initialization failed');}
 private id(element:number,index:number):number{const key=`${element}:${index}`;if(!this.ids.has(key))this.ids.set(key,this.ids.size);return this.ids.get(key)!;}
 push(bytes:Uint8Array):void{if(this.dead)throw codecFailure("iamf.failure_03",'IAMF decoder closed');try{this.feed(bytes);}catch(e){this.free();throw e;}}
 private feed(bytes:Uint8Array):void{
  const b=new Uint8Array(this.pending.length+bytes.length);b.set(this.pending);b.set(bytes,this.pending.length);let end=0;
  // Only submit complete OBUs; the native parser is stateful on partial input.
  while(end<b.length){const h=b[end]!,r=leb(b,end+1);if(!r)break;const [size,start]=r;if(size>16*1024*1024)throw codecFailure("iamf.failure_04",'IAMF OBU exceeds 16 MiB');if(start+size>b.length)break;
   let p=start;const read=()=>{const r=leb(b.subarray(0,start+size),p);if(!r)throw codecFailure("iamf.failure_05",'IAMF truncated descriptor');p=r[1];return r[0];};
   if(h&2){read();read();}if(h&1){const n=read();p+=n;}if(p>start+size)throw codecFailure("iamf.failure_06",'IAMF invalid header');
   if(h>>3===0){read();const codec=String.fromCharCode(...b.subarray(p,p+4));p+=4;const frame=read();p+=2;
    if(codec!=='ipcm')throw codecFailure("iamf.failure_07",`IAMF 暂不支持 ${codec} 编码；当前支持 LPCM`);
    if(p+6>start+size||frame<1||frame>16384)throw codecFailure("iamf.failure_08",'IAMF invalid LPCM configuration');
    const rate=new DataView(b.buffer).getUint32(p+2);if(rate!==48000)throw codecFailure("iamf.failure_09",`IAMF 当前支持 48000 Hz，文件为 ${rate} Hz`);
   }
   end=start+size;
  }
  let cursor=0;
  while(cursor<end){const n=end-cursor,m=runtime,p=m._sda_input(n);if(!p)throw codecFailure("iamf.failure_10",'IAMF allocation failed');m.HEAPU8.set(b.subarray(cursor,end),p);const error=m._sda_decode(n),used=m._sda_info(0);if(error)codecCheckpoint("iamf.decode_status",{code:error,used,bytes:n});
   if(error&&error!==-2)throw codecFailure("iamf.failure_11",`IAMF decode failed (${error})`);if(used<0||used>n)throw codecFailure("iamf.failure_12",'IAMF invalid consumption');this.takeFrame();cursor+=used;if(!used)break;
  }
  this.pending=b.slice(cursor);if(this.pending.length>32*1024*1024)throw codecFailure("iamf.failure_13",'IAMF decoder stalled');
 }
 private takeFrame():void{
  const m=runtime,n=m._sda_info(1);if(n<=0)return;const trim=m._sda_info(5),labels=[...beds],channels=beds.map(()=>new Float32Array(n)),objectChannels:{id:number;channel:number}[]=[],events:ObjectEvent[]=[];
  const pcm=m._sda_output()/4;for(let s=0;s<n;s++)for(let c=0;c<12;c++)channels[c]![s]=m.HEAP32[pcm+s*12+c]/2147483648;
  for(let i=0;i<m._sda_info(2);i++){const element=m._sda_object_info(i,0)>>>0,count=m._sda_object_info(i,1),length=m._sda_object_info(i,2),p=m._sda_object_pcm(i)/4;if(trim+n>length)throw codecFailure("iamf.failure_14",'IAMF object trim mismatch');
   for(let c=0;c<count;c++){const id=this.id(element,c);objectChannels.push({id,channel:channels.length});labels.push(`Obj_${id}`);channels.push(m.HEAPF32.slice(p+c*length+trim,p+c*length+trim+n));}
  }
  const ep=m._sda_events()/4;
  for(let i=0;i<m._sda_info(3);i++){const p=ep+i*7,e=m.HEAPF32,offset=e[p+2]-trim,duration=e[p+3];if(offset>=n||offset+duration<=0)continue;const id=this.id(m.HEAP32[p]>>>0,e[p+1]),az=e[p+4]*Math.PI/180,el=e[p+5]*Math.PI/180,r=e[p+6];
   events.push({id,samplePos:this.samplePos+Math.max(0,offset),hasPos:true,pos:[-Math.sin(az)*Math.cos(el)*r,Math.cos(az)*Math.cos(el)*r,Math.sin(el)*r],gainDb:0,size:[0,0,0],anchor:'room',distanceM:null,distanceInfinite:false,screenFactor:null,depthFactor:null,rampDuration:0});
  }
  if(objectChannels.some(o=>!events.some(e=>e.id===o.id)))throw codecFailure("iamf.failure_15",'IAMF object audio has no position metadata');
  this.frames.push({codec:'iamf',sampleRate:48000,samplePos:this.samplePos,channels,labels,rawBedLabels:[...beds],events,objectChannels,programLoudness:null,rampDuration:0});this.samplePos+=n;
 }
 nextFrame():DecodedFrameData|null{return this.frames.shift()??null;}
 drainErrors():string[]{return [];}
 flush():void{if(this.dead)throw codecFailure("iamf.failure_16",'IAMF decoder closed');if(this.pending.length)throw codecFailure("iamf.failure_17",'IAMF truncated stream');if(!runtime._sda_info(4))throw codecFailure("iamf.failure_18",'IAMF missing descriptors');const e=runtime._sda_decode(0);if(e&&e!==-2)throw codecFailure("iamf.failure_19",`IAMF flush failed (${e})`);this.takeFrame();}
 free():void{if(!this.dead){runtime._sda_close();this.dead=true;this.frames=[];this.pending=new Uint8Array(0);}}
}
