/**
 * @sda/core — TypeScript facade over the wasm-bindgen output in ../pkg-web.
 *
 * The wasm module must be initialised once (`initCore`) before constructing
 * decoders. In Vite/Electron, pass nothing — the pkg `.wasm` is fetched via
 * `new URL(...)` so the bundler emits it as an asset.
 */

// @ts-ignore — generated by wasm-bindgen, see scripts/build-core.mjs
import init, { SdaDecoder as WasmDecoder } from "../pkg-web/sda_core.js";
// @ts-ignore
import wasmUrl from "../pkg-web/sda_core_bg.wasm?url";

export type CodecName = "auto" | "truehd" | "eac3" | "dts" | "alac";

export type ObjectAnchor = "room" | "screen" | "speaker";

/** One dynamic-object spatial event (ADM cartesian plus codec render metadata). */
export interface ObjectEvent {
  id: number;
  samplePos: number;
  hasPos: boolean;
  /** ADM cartesian [x, y, z]: x+ = right, y+ = front, z+ = up
   *  (ITU-R BS.2076 / EBU EAR / Omniphony 约定). */
  pos: [number, number, number];
  gainDb: number;
  /** (width, depth, height) each normalised to [0, 1]; [0,0,0] = point source. */
  size: [number, number, number];
  /** Real codec render metadata. Speaker anchors are bed/ISF semantics. */
  anchor: ObjectAnchor;
  /** Finite codec distance in metres; absent when the stream does not provide it. */
  distanceM: number | null;
  distanceInfinite: boolean;
  screenFactor: number | null;
  depthFactor: number | null;
  rampDuration: number;
}

export interface ObjectChannelDecl {
  id: number;
  channel: number;
}

export interface ProgramLoudnessMetadata {
  source: "eac3-dialnorm" | "truehd-dialogue-norm";
  dialogueLevelDb: number;
  targetDb: -31;
  gainDb: number;
}

export interface DecodedFrameData {
  codec: string;
  sampleRate: number;
  samplePos: number;
  channels: Float32Array[];
  labels: string[];
  /** Original fixed bed labels before object reconstruction/downstream routing. */
  rawBedLabels: string[];
  events: ObjectEvent[];
  objectChannels: ObjectChannelDecl[];
  programLoudness: ProgramLoudnessMetadata | null;
  rampDuration: number;
}

let initPromise: Promise<unknown> | null = null;

export function initCore(): Promise<unknown> {
  initPromise ??= init(wasmUrl);
  return initPromise;
}

/**
 * Streaming decoder. `push()` any chunking of the raw bitstream, then drain
 * with `nextFrame()`. Decoders resync on errors — check `drainErrors()`.
 */
export class SdaDecoder {
  private inner: WasmDecoder;

  constructor(codec: Exclude<CodecName, "alac"> = "auto") {
    this.inner = new WasmDecoder(codec);
  }

  /** Create a decoder that requires container initialization data. ALAC needs
   * the complete MP4 `alac` codec atom before its first access unit. */
  static withConfig(codec: "alac", config: Uint8Array): SdaDecoder {
    const decoder = Object.create(SdaDecoder.prototype) as SdaDecoder;
    decoder.inner = WasmDecoder.withConfig(codec, config);
    return decoder;
  }

  get codec(): string {
    return this.inner.codec;
  }

  push(data: Uint8Array): void {
    this.inner.push(data);
  }

  nextFrame(): DecodedFrameData | null {
    const frame = this.inner.nextFrame();
    if (!frame) return null;
    const channels: Float32Array[] = [];
    for (let i = 0; i < frame.channelCount; i++) {
      const ch = frame.channel(i);
      if (ch) channels.push(ch);
    }
    const data: DecodedFrameData = {
      codec: frame.codec,
      sampleRate: frame.sampleRate,
      samplePos: frame.samplePos,
      channels,
      labels: frame.labels,
      rawBedLabels: frame.rawBedLabels,
      events: JSON.parse(frame.eventsJson) as ObjectEvent[],
      objectChannels: JSON.parse(frame.objectChannelsJson) as ObjectChannelDecl[],
      programLoudness: JSON.parse(frame.programLoudnessJson) as ProgramLoudnessMetadata | null,
      rampDuration: frame.rampDuration,
    };
    frame.free();
    return data;
  }

  drainErrors(): string[] {
    return this.inner.drainErrors();
  }

  reset(): void {
    this.inner.reset();
  }

  free(): void {
    this.inner.free();
  }
}
