import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const source = readFileSync(join(import.meta.dirname, "../src/player.ts"), "utf8");
assert.match(source, /export interface NativeRendererSink/);
assert.match(source, /nativeRendererSink\?: NativeRendererSink/);
assert.match(source, /this\.nativeRendererSink = options\.nativeRendererSink/);
assert.match(source, /this\.nativeRendererSink(?:\?|!)\.events\(events\)/);
assert.match(source, /export interface NativeRendererSourceDeclaration/);
assert.match(source, /bedLabel\?: string/);
assert.match(source, /this\.nativeRendererSink\?\.addSource\(\{ id, atSample: frame\.samplePos, bedLabel: label \}\)/);
assert.match(source, /this\.nativeRendererSink!\.addSource\(source\)/);
assert.match(source, /this\.nativeRendererSink(?:\?|!)\.frame\(frame\.samplePos, entries\)/);
assert.match(source, /const labelObjects: ObjectChannelDecl\[\] = frame\.labels\.flatMap/);
assert.match(source, /const declarations = declaredObjects\.length > 0 \? declaredObjects : labelObjects/);
assert.match(source, /else if \(!hasObjectLabels\)/);
assert.match(source, /sidecar accepted or rejected the entire codec batch/);
assert.match(source, /this\.nativeRendererSink\?\.setHeadPose\(pose\)/);
assert.match(source, /this\.nativeRendererSink\?\.setLfeMuted\(muted\)/);
assert.match(source, /this\.nativeRendererSink\?\.setVolume\(v\)/);
assert.match(source, /this\.nativeRendererSink\?\.setProgramEnabled\(enabled\)/);
assert.match(source, /this\.nativeRendererSink\?\.setProgramGainDb\(gainDb, atSample\)/);
assert.match(source, /this\.nativeRendererSink\?\.setBinauralEq\(/);
assert.match(source, /this\.nativeRendererSink\?\.setHeadphoneProfile\(profileId\)/);
assert.match(source, /setLayout\(layout: LayoutId\)/);
assert.match(source, /setLayout\(layout: LayoutId\): void \| Promise<void>/);
assert.match(source, /this\.nativeRendererSink\?\.setLayout\(layoutIdFor\(layout\)\)/);
assert.match(source, /await this\.nativeRendererSink\?\.setLayout\(layoutIdFor\(layout \?\? LAYOUTS\["7\.1\.4"\]\)\)/);
assert.match(source, /initialAutoLayout = true/);
assert.match(source, /this\.autoLayoutEnabled = initialAutoLayout/);
assert.match(source, /this\.setLfeMuted\(this\.lfeMuted\)/);
assert.match(source, /this\.nativeRendererSink\?\.clearHeadPose\(\)/);
assert.match(source, /this\.nativeRendererSink\?\.startAt\(this\.startupOrigin\)/);
assert.match(source, /this\.nativeRendererSink\?\.pause\(true\)/);
assert.match(source, /this\.nativeRendererSink\?\.pause\(false\)/);
assert.match(source, /onObjectActivity\?\(callback: \(ids: readonly number\[\]\)/);
assert.match(source, /this\.installNativeObjectActivity\(\)/);
assert.match(source, /sink\.onObjectActivity\?\.\(\(ids\) => this\.handleObjectActivity/);
assert.match(source, /this\.nativeObjectActivityUnsubscribe\?\.\(\)/);
assert.match(source, /native renderer frame mirror failed/);
assert.match(source, /this\.renderer\.feedBatch\(sequence, frame\.samplePos, entries\)/);

console.log("native renderer mirror contract tests passed");
