import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { build } from 'esbuild';
const result = await build({ entryPoints: ['apps/mobile/src/ios-ui-model.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { IOS_TABS, playbackStatus, compatibleRooms, isPresetSelected, trackTitle } = await import('data:text/javascript;base64,' + Buffer.from(result.outputFiles[0].text).toString('base64'));
assert.deepEqual(IOS_TABS, ['播放', '资料库', '空间']);
assert.equal(trackTitle({name:'file.m4a',metadata:{title:'Song'}}),'Song');
assert.equal(trackTitle({name:'file.m4a',metadata:{}}),'file.m4a');
const ready = {busy:false,preparingAudio:false,playing:false,paused:false,ended:false,selectedUri:'file'};
assert.equal(playbackStatus(ready),'准备就绪');
assert.equal(playbackStatus({...ready,playing:true}),'播放中');
assert.equal(playbackStatus({...ready,playing:true,paused:true}),'已暂停');
assert.equal(playbackStatus({...ready,playing:true,preparingAudio:true}),'正在准备音频…');
assert.equal(playbackStatus({...ready,ended:true}),'播放结束');
const rooms=[{id:'13',layout:'360RA-13'},{id:'12',layout:'7.1.4'}];
assert.deepEqual(compatibleRooms({rooms,layout:'7.1.4',systemSpatial360RAActive:true,systemSpatial360RA:false}),[rooms[0]]);
assert.deepEqual(compatibleRooms({rooms,layout:'7.1.4',systemSpatial360RAActive:true,systemSpatial360RA:true}),[rooms[1]]);
const preset={hrtfSet:'standard',direct:true,directional:true,nearField:false,roomId:'',hrtfWetWeight:.04};
const state={...preset,directObjects:true,directionalObjects:true};
assert.ok(isPresetSelected(state,preset));
assert.ok(!isPresetSelected({...state,directionalObjects:false},preset));
assert.ok(!isPresetSelected({...state,roomId:'13'},preset));
const ui=readFileSync('apps/mobile/src/IOSPlayer.tsx','utf8');
assert.match(ui, /<MobileObjectScene layout={p.layout} objects={p.objects}/);
assert.ok(ui.includes('"gearshape", "更多设置", () => setSettings(true)'));
assert.match(ui, /accessibilityViewIsModal/);
assert.ok(ui.includes('"chevron.left", "返回", () => setSettings(false)'));
assert.match(readFileSync('apps/mobile/App.tsx','utf8'), /copyToCacheDirectory: *true/);
assert.match(readFileSync('apps/mobile/modules/sda-core/ios/GlassControls.swift','utf8'), /["播放", "资料库", "空间"]/);
console.log('iOS UI regression checks passed: navigation, status, original 360RA rooms, presets, real scene, safe import');
