import assert from 'node:assert/strict';
import monitor from '../monitor-settings.cjs';
import cinema from '../cinema-profiles.cjs';
const legacy={enabled:true,directDb:0,earlyDb:0,lateDb:0,earlyMs:50,bassEnabled:true,crossoverHz:85,bassDb:-3,speakers:{}};
const migrated=cinema.validateSettings(legacy);
assert.equal(migrated.monitor.enabled,true);
assert.equal(migrated.monitor.crossoverHz,85);
assert.equal(migrated.bassEnabled,false);
assert.deepEqual(cinema.validateSettings(migrated),migrated);
const off=cinema.validateSettings({...migrated,enabled:false});
assert.deepEqual(off.monitor,migrated.monitor,'room bypass must not disable monitor');
assert.throws(()=>monitor.validate({...monitor.defaults(),levelDb:NaN}));
assert.throws(()=>monitor.validate({...monitor.defaults(),outputs:{Unknown:{trimDb:0,delayMs:0,invert:false,muted:false}}}));
const valid={...monitor.defaults(),outputs:{LFE:{trimDb:-6,delayMs:2,invert:true,muted:false}}};
assert.deepEqual(monitor.validate(valid),valid);
console.log('Monitor validation, migration and room independence passed');
const hardware=monitor.validate({...monitor.defaults(),hardware:{enabled:true}}).hardware;
assert.equal(hardware.enabled,true);
assert.equal(hardware.lineRms,2);
assert.throws(()=>monitor.validate({...monitor.defaults(),hardware:{dacBits:8.5}}));
assert.throws(()=>monitor.validate({...monitor.defaults(),hardware:{currentA:NaN}}));
assert.deepEqual(cinema.validateSettings({...legacy,enabled:false,monitor:{...monitor.defaults(),hardware}}).monitor.hardware,hardware);
